title: Exploration into two decades of school shootings in the United States
description: >-
  
baseurl: "/school-shootings-analysis"
url: "https://julzerinos.github.io" 

# Build settings
remote_theme: riggraz/no-style-please
plugins:
  - jekyll-feed
